"""pmrf/simulate/base.py"""

import numpy as np
from abc import abstractmethod
import equinox as eqx
import jax.numpy as jnp
from typing import Any


class NodalRepresentation(eqx.Module):
    """
    Static topological representation for nodal admittance assembly and reduction.
    """
    #: A 1D array of global row indices mapping local elements to the global Nodal Admittance Matrix (NAM).
    r_idx: np.ndarray

    #: A 1D array of global column indices mapping local elements to the global NAM.
    c_idx: np.ndarray

    #: A 1D array of node indices designated as external (retained after reduction).
    ext_idx: np.ndarray

    #: A 1D array of node indices designated as internal (eliminated via Schur complement).
    int_idx: np.ndarray

    @property
    def num_nodes(self) -> int:
        """The total number of global nodes in the network, including the dummy ground node."""
        return self.ext_idx.shape[0] + self.int_idx.shape[0]    


class MNARepresentation(eqx.Module):
    """
    Static topological representation for Modified Nodal Analysis (MNA) assembly and reduction.
    """
    #: Global row indices mapping local Y elements (Node to Node) to the global MNA matrix.
    y_r_idx: np.ndarray
    #: Global column indices mapping local Y elements (Node to Node) to the global MNA matrix.
    y_c_idx: np.ndarray

    #: Global row indices mapping local B elements (Node to Aux) to the global MNA matrix.
    b_r_idx: np.ndarray
    #: Global column indices mapping local B elements (Node to Aux) to the global MNA matrix.
    b_c_idx: np.ndarray

    #: Global row indices mapping local C elements (Aux to Node) to the global MNA matrix.
    c_r_idx: np.ndarray
    #: Global column indices mapping local C elements (Aux to Node) to the global MNA matrix.
    c_c_idx: np.ndarray

    #: Global row indices mapping local D elements (Aux to Aux) to the global MNA matrix.
    d_r_idx: np.ndarray
    #: Global column indices mapping local D elements (Aux to Aux) to the global MNA matrix.
    d_c_idx: np.ndarray

    #: A 1D array of standard node indices designated as external (retained after reduction).
    ext_idx: np.ndarray

    #: A 1D array of standard node indices designated as internal (eliminated).
    int_idx: np.ndarray

    #: A 1D array of auxiliary indices (inherently internal and eliminated).
    aux_idx: np.ndarray 

    @property
    def num_nodes(self) -> int:
        """The total number of global standard nodes in the network."""
        return self.ext_idx.shape[0] + self.int_idx.shape[0]

    @property
    def num_aux(self) -> int:
        """The total number of global auxiliary variables."""
        return self.aux_idx.shape[0]


class PortRepresentation(eqx.Module):
    """
    Static topological representation for scattering parameter connection and reduction.
    """
    #: A 1D array of port indices designated as external (unconnected or specifically retained).
    ext_idx: np.ndarray

    #: A 1D array of port indices designated as internal (connected to other ports).
    int_idx: np.ndarray

    #: A 1D array of length `num_ports` mapping each port to the integer ID of its connected net.
    port_to_net_map: np.ndarray

    @property
    def num_ports(self) -> int:
        """The total number of ports across all components in the topology."""
        return self.port_to_net_map.shape[0]    


class ScatteringResult(eqx.Module):
    """
    Data container for the result of a scattering simulation.
    """
    #: The resulting S-parameter matrix.
    s: jnp.ndarray

    #: The characteristic reference impedance of the resulting S-matrix.
    z0: jnp.ndarray

    #: Indicates whether the solver completed successfully, by default True.
    success: bool = True

    #: Arbitrary metrics or diagnostic data generated by the solver, by default None.
    metrics: Any = None


class AdmittanceResult(eqx.Module):
    """
    Data container for the result of an admittance simulation.
    """
    #: The resulting Admittance (Y-parameter) matrix.
    y: jnp.ndarray

    #: Indicates whether the solver completed successfully, by default True.
    success: bool = True

    #: Arbitrary metrics or diagnostic data generated by the solver, by default None.
    metrics: Any = None


class ABCDResult(eqx.Module):
    """
    Data container for the result of a ABCD parameter simulation/reduction.
    """
    #: The resulting ABCD matrix.
    a: jnp.ndarray
    
    #: Indicates whether the solver completed successfully, by default True.
    success: bool = True

    #: Arbitrary metrics or diagnostic data generated by the solver, by default None.
    metrics: Any = None


class AbstractAdmittanceReducer(eqx.Module):
    """Abstract base class for solvers that reduce arbitrary networks in the Admittance domain."""
    
    @abstractmethod
    def run(
        self, 
        y_flattened: jnp.ndarray,
        topology: NodalRepresentation, 
    ) -> AdmittanceResult:
        """
        Executes the admittance reduction algorithm.

        Parameters
        ----------
        y_flattened : jnp.ndarray
            A 1D array of flattened Y-parameter matrix elements.
        topology : NodalRepresentation
            The static map dictating the nodal assembly and partition logic.

        Returns
        -------
        AdmittanceResult
            The fully reduced Y-parameter result.
        """
        raise NotImplementedError
    

class AbstractMNAReducer(eqx.Module):
    """Abstract base class for solvers that reduce arbitrary admittance using MNA."""
    
    @abstractmethod
    def run(
        self, 
        y_flattened: jnp.ndarray,
        b_flattened: jnp.ndarray,
        c_flattened: jnp.ndarray,
        d_flattened: jnp.ndarray,
        topology: MNARepresentation, 
    ) -> AdmittanceResult:
        """
        Executes the Modified Nodal Analysis reduction algorithm.

        Parameters
        ----------
        y_flattened : jnp.ndarray
            A 1D array of flattened Y-block elements.
        b_flattened : jnp.ndarray
            A 1D array of flattened B-block elements.
        c_flattened : jnp.ndarray
            A 1D array of flattened C-block elements.
        d_flattened : jnp.ndarray
            A 1D array of flattened D-block elements.
        topology : MNARepresentation
            The static map dictating the MNA assembly and partition logic.

        Returns
        -------
        AdmittanceResult
            The fully reduced external Y-parameter matrix.
        """
        raise NotImplementedError
    

class AbstractScatteringReducer(eqx.Module):
    """Abstract base class for solvers that reduce arbitrary networks in the Scattering domain."""
    
    @abstractmethod
    def run(
        self, 
        s_block_diagonal: jnp.ndarray,
        z0_ports: jnp.ndarray,
        topology: PortRepresentation, 
    ) -> ScatteringResult:
        """
        Executes the scattering reduction algorithm.

        Note on Dangling Ports
        ----------------------
        Implementations MUST safely handle mathematically isolated external ports (where a port 
        in `topology.ext_idx` is the ONLY port on its defined net). To prevent solvers from 
        evaluating these as perfect open circuits (S=1.0), implementations should dynamically inject 
        matched virtual VNA probes (e.g., padding the S-matrix with 0.0s and rewiring the indices) 
        prior to solving.

        Parameters
        ----------
        s_block_diagonal : jnp.ndarray
            A 2D array of shape (N_total, N_total) containing the uncoupled S-parameters 
            of all components placed sequentially along the main diagonal. All off-diagonal 
            elements are exactly zero.
        z0_ports : jnp.ndarray
            A 1D array of shape (N_total,) containing the characteristic impedances for all ports.
        topology : PortRepresentation
            The static map dictating the port connections, nets, and partition logic.

        Returns
        -------
        ScatteringResult
            The fully reduced S-parameter result.
        """
        raise NotImplementedError
    

class AbstractScatteringCascader(eqx.Module):
    """Abstract base class for solvers that cascade sequential networks in the Scattering domain."""
    
    @abstractmethod
    def run(
        self, 
        s_stacked: jnp.ndarray,
        port_z0: jnp.ndarray,
    ) -> ScatteringResult:
        """
        Executes the scattering cascade algorithm.

        Parameters
        ----------
        s_stacked : jnp.ndarray
            A 3D array of shape (N_models, n_ports, n_ports) representing sequential networks.
        port_z0 : jnp.ndarray
            A 2D array of shape (N_models, n_ports) representing sequential port impedances.

        Returns
        -------
        ScatteringResult
            The completely cascaded S-parameter result.
        """
        raise NotImplementedError
    

class AbstractABCDCascader(eqx.Module):
    """Abstract base class for solvers that cascade sequential networks in the ABCD domain."""
    
    @abstractmethod
    def run(
        self, 
        a_stacked: jnp.ndarray,
    ) -> ABCDResult:
        """
        Executes the ABCD parameter cascade algorithm.

        Parameters
        ----------
        a_stacked : jnp.ndarray
            A 3D array of shape (N_models, n_ports, n_ports) representing sequential networks.

        Returns
        -------
        ABCDResult
            The completely cascaded ABCD parameter result.
        """
        raise NotImplementedError
    

class AbstractScatteringTerminator(eqx.Module):
    """Abstract base class for algorithms terminating S-parameters into S-parameters."""
    
    @abstractmethod
    def run(
        self, 
        s_from: jnp.ndarray, 
        z0_from: jnp.ndarray, 
        s_into: jnp.ndarray, 
        z0_into: jnp.ndarray
    ) -> ScatteringResult:
        """
        Executes the scattering parameter termination algorithm.

        Parameters
        ----------
        s_from : jnp.ndarray
            The primary S-matrix being terminated.
        z0_from : jnp.ndarray
            The characteristic impedances of `s_from`.
        s_into : jnp.ndarray
            The load S-matrix.
        z0_into : jnp.ndarray
            The characteristic impedances of `s_into`.

        Returns
        -------
        ScatteringResult
            The resulting S-parameter matrix after termination.
        """
        raise NotImplementedError


class AbstractABCDTerminator(eqx.Module):
    """Abstract base class for algorithms terminating ABCD parameters into S-parameters."""
    
    @abstractmethod
    def run(
        self, 
        a_from: jnp.ndarray, 
        s_into: jnp.ndarray, 
        z0_into: jnp.ndarray
    ) -> ScatteringResult:
        """
        Executes the ABCD-to-scattering termination algorithm.

        Parameters
        ----------
        a_from : jnp.ndarray
            The primary ABCD matrix being terminated.
        s_into : jnp.ndarray
            The load S-matrix.
        z0_into : jnp.ndarray
            The characteristic impedance of the resulting terminated matrix.

        Returns
        -------
        ScatteringResult
            The resulting S-parameter matrix after termination.
        """
        raise NotImplementedError


# Type Aliases for solver categories
AbstractReducer = AbstractAdmittanceReducer | AbstractScatteringReducer | AbstractMNAReducer
AbstractCascader = AbstractScatteringCascader | AbstractABCDCascader
AbstractTerminator = AbstractScatteringTerminator | AbstractABCDTerminator