"""pmrf/simulate/base.py"""

import numpy as np
from abc import abstractmethod
import equinox as eqx
import jax.numpy as jnp
from typing import Any


class NodalRepresentation(eqx.Module):
    """
    Static topological representation for nodal admittance assembly and reduction.

    Attributes
    ----------
    num_nodes : int
        The total number of global nodes in the network, including the dummy ground node.
    r_idx : np.ndarray
        A 1D array of global row indices mapping local elements to the global Nodal Admittance Matrix (NAM).
    c_idx : np.ndarray
        A 1D array of global column indices mapping local elements to the global NAM.
    ext_idx : np.ndarray
        A 1D array of node indices designated as external (retained after reduction).
    int_idx : np.ndarray
        A 1D array of node indices designated as internal (eliminated via Schur complement).
    """
    num_nodes: int = eqx.field(static=True)
    r_idx: np.ndarray
    c_idx: np.ndarray
    ext_idx: np.ndarray
    int_idx: np.ndarray

class PortRepresentation(eqx.Module):
    """
    Static topological representation for scattering parameter connection and reduction.

    Attributes
    ----------
    num_ports : int
        The total number of ports across all components in the topology.
    ext_idx : np.ndarray
        A 1D array of port indices designated as external (unconnected or specifically retained).
    int_idx : np.ndarray
        A 1D array of port indices designated as internal (connected to other ports).
    port_to_net_map : np.ndarray
        A 1D array of length `num_ports` mapping each port to the integer ID of its connected net.
    """
    num_ports: int = eqx.field(static=True)
    ext_idx: np.ndarray
    int_idx: np.ndarray
    port_to_net_map: np.ndarray

class ScatteringResult(eqx.Module):
    """
    Data container for the result of a scattering parameter simulation/reduction.

    Attributes
    ----------
    s : jnp.ndarray
        The resulting S-parameter matrix.
    z0 : jnp.ndarray
        The characteristic reference impedance of the resulting S-matrix.
    success : bool, optional
        Indicates whether the solver completed successfully, by default True.
    metrics : Any, optional
        Arbitrary metrics or diagnostic data generated by the solver, by default None.
    """
    s: jnp.ndarray
    z0: jnp.ndarray
    
    success: bool = True
    metrics: Any = None

class AdmittanceResult(eqx.Module):
    """
    Data container for the result of an admittance parameter simulation/reduction.

    Attributes
    ----------
    y : jnp.ndarray
        The resulting Admittance (Y-parameter) matrix.
    success : bool, optional
        Indicates whether the solver completed successfully, by default True.
    metrics : Any, optional
        Arbitrary metrics or diagnostic data generated by the solver, by default None.
    """
    y: jnp.ndarray
    
    success: bool = True
    metrics: Any = None

class TransferResult(eqx.Module):
    """
    Data container for the result of a transfer (ABCD) parameter simulation/reduction.

    Attributes
    ----------
    a : jnp.ndarray
        The resulting Transfer (ABCD-parameter) matrix.
    success : bool, optional
        Indicates whether the solver completed successfully, by default True.
    metrics : Any, optional
        Arbitrary metrics or diagnostic data generated by the solver, by default None.
    """
    a: jnp.ndarray
    
    success: bool = True
    metrics: Any = None


class AbstractAdmittanceReducer(eqx.Module):
    """Abstract base class for solvers that reduce arbitrary networks in the Admittance domain."""
    
    @abstractmethod
    def run(
        self, 
        y_flattened: jnp.ndarray,
        topology: NodalRepresentation, 
    ) -> AdmittanceResult:
        """
        Executes the admittance reduction algorithm.

        Parameters
        ----------
        y_flattened : jnp.ndarray
            A 1D array of flattened Y-parameter matrix elements.
        topology : NodalRepresentation
            The static map dictating the nodal assembly and partition logic.

        Returns
        -------
        AdmittanceResult
            The fully reduced Y-parameter result.
        """
        raise NotImplementedError
    
class AbstractScatteringReducer(eqx.Module):
    """Abstract base class for solvers that reduce arbitrary networks in the Scattering domain."""
    
    @abstractmethod
    def run(
        self, 
        s_block_diagonal: jnp.ndarray,
        port_z0: jnp.ndarray,
        topology: PortRepresentation, 
    ) -> ScatteringResult:
        """
        Executes the scattering reduction algorithm.

        Parameters
        ----------
        s_block_diagonal : jnp.ndarray
            The S-parameters assembled into a global block-diagonal matrix space.
        port_z0 : jnp.ndarray
            The characteristic impedances for all global ports.
        topology : PortRepresentation
            The static map dictating the port connections and partition logic.

        Returns
        -------
        ScatteringResult
            The fully reduced S-parameter result.
        """
        raise NotImplementedError
    
class AbstractScatteringCascader(eqx.Module):
    """Abstract base class for solvers that cascade sequential networks in the Scattering domain."""
    
    @abstractmethod
    def run(
        self, 
        s_stacked: jnp.ndarray,
        port_z0: jnp.ndarray,
    ) -> ScatteringResult:
        """
        Executes the scattering cascade algorithm.

        Parameters
        ----------
        s_stacked : jnp.ndarray
            A 3D tensor of shape (N_models, N_ports, N_ports) representing sequential networks.
        port_z0 : jnp.ndarray
            A 2D tensor of shape (N_models, N_ports) representing sequential port impedances.

        Returns
        -------
        ScatteringResult
            The completely cascaded S-parameter result.
        """
        raise NotImplementedError
    
class AbstractTransferCascader(eqx.Module):
    """Abstract base class for solvers that cascade sequential networks in the Transfer domain."""
    
    @abstractmethod
    def run(
        self, 
        a_stacked: jnp.ndarray,
    ) -> TransferResult:
        """
        Executes the transfer parameter cascade algorithm.

        Parameters
        ----------
        a_stacked : jnp.ndarray
            A 3D tensor of shape (N_models, N_ports, N_ports) representing sequential networks.

        Returns
        -------
        TransferResult
            The completely cascaded Transfer (ABCD) parameter result.
        """
        raise NotImplementedError
    
class AbstractScatteringTerminator(eqx.Module):
    """Abstract base class for algorithms terminating S-parameters into S-parameters."""
    
    @abstractmethod
    def run(
        self, 
        s_from: jnp.ndarray, 
        z0_from: jnp.ndarray, 
        s_into: jnp.ndarray, 
        z0_into: jnp.ndarray
    ) -> ScatteringResult:
        """
        Executes the scattering parameter termination algorithm.

        Parameters
        ----------
        s_from : jnp.ndarray
            The primary S-matrix being terminated.
        z0_from : jnp.ndarray
            The characteristic impedances of `s_from`.
        s_into : jnp.ndarray
            The load S-matrix.
        z0_into : jnp.ndarray
            The characteristic impedances of `s_into`.

        Returns
        -------
        ScatteringResult
            The resulting S-parameter matrix after termination.
        """
        raise NotImplementedError

class AbstractTransferTerminator(eqx.Module):
    """Abstract base class for algorithms terminating Transfer parameters into S-parameters."""
    
    @abstractmethod
    def run(
        self, 
        a_from: jnp.ndarray, 
        s_into: jnp.ndarray, 
        z0_into: jnp.ndarray
    ) -> ScatteringResult:
        """
        Executes the transfer-to-scattering termination algorithm.

        Parameters
        ----------
        a_from : jnp.ndarray
            The primary Transfer (ABCD) matrix being terminated.
        s_into : jnp.ndarray
            The load S-matrix.
        z0_into : jnp.ndarray
            The characteristic impedance of the resulting terminated matrix.

        Returns
        -------
        ScatteringResult
            The resulting S-parameter matrix after termination.
        """
        raise NotImplementedError

# Type Aliases for solver categories
AbstractReducer = AbstractAdmittanceReducer | AbstractScatteringReducer
AbstractCascader = AbstractScatteringCascader | AbstractTransferCascader
AbstractTerminator = AbstractScatteringTerminator | AbstractTransferTerminator