[project]
name = "paramrf"
version = "0.10.1"
description = "ParamRF: Parametric Radio Frequency Modelling, Fitting and Sampling"
readme = "README.md"
authors = [
    { name = "Gary Allen", email = "gvcallen@gmail.com" }
]
dependencies = [
    "equinox",
    "jax",
    "jaxtyping",
    "h5py",
    "matplotlib",
    "numpy",
    "numpyro",
    "jsonpickle",
    "cloudpickle",
    "scikit-rf",
    "scipy",
    "joblib",
]

[project.optional-dependencies]
polychord = [
    "pypolychord @ git+https://github.com/PolyChord/PolyChordLite.git",
    "anesthetic",
    "fgivenx",
    "mpi4py",
    "pandas",
]
dypolychord = [
    "dyPolyChord",
    "anesthetic",
    "fgivenx",
    "mpi4py",
    "pandas",
]
blackjax = [
    "blackjax @ git+https://github.com/handley-lab/blackjax@nested_sampling",
    "anesthetic",
    "pandas",
    "tqdm",
]
eqxlearn = [
    "eqx-learn @ git+https://github.com/eqx-learn/eqx-learn",
]
docs = [
    "sphinx",
    "myst-parser",
    "ghp-import",
    "sphinx-rtd-theme",
    "sphinx-math-dollar",
]

[project.urls]
homepage = "https://github.com/paramrf/paramrf"

[build-system]
requires = [
    "setuptools>=45",
    "wheel",
    "setuptools_scm[toml]>=6.2",
]
build-backend = 'setuptools.build_meta'

[tool.setuptools.packages.find]
include = ["pmrf"]