[project]
name = "paramrf"
version = "0.15.4"
description = "Parametric radio frequency modelling, optimization and sampling"
readme = "README.rst"
authors = [
    { name = "Gary Allen", email = "gvcallen@gmail.com" }
]
dependencies = [
    "jax",
    "jaxtyping",
    "equinox",
    "parax",
    "distreqx",
    "optimistix",
    "inferix",
    "numpy",
    "scipy",
    "scikit-rf",
    "tqdm",
]

[project.optional-dependencies]
docs = [
    "sphinx",
    "nbsphinx",
    "pandoc",
    "myst-parser",
    "ghp-import",
    "sphinx-rtd-theme",
    "sphinx-math-dollar",
    "ipython",
]
tests = [
    "pytest",
    "ipython",
    "scikit-rf",
]

[project.urls]
homepage = "https://github.com/gvcallen/paramrf"

[build-system]
requires = [
    "setuptools>=45",
    "wheel",
    "setuptools_scm[toml]>=6.2",
]
build-backend = 'setuptools.build_meta'

[tool.setuptools.packages.find]
include = ["pmrf"]
