from functools import reduce
from typing import Any, Callable, Dict
import re

import pmrf.numpy as np
from numpy import ndindex
import jax
from jax.tree_util import GetAttrKey
import equinox as eqx


def tree_with_params(
    tree: Any,
    flat_params: jax.Array | None = None,
    separator: str | None = '_',
    subtree_separator: str | None = None,
    array_separator: str | None = None,
    index_separator: str | None = None,
    param_filter: Callable[[Any], bool] | None = None,
    **params: Any
) -> Any:
    """
    Returns a new tree with updated parameter values.

    This function supports two calling styles:
    1. By keyword: `tree_with_parameters(model, sub_R=50.0, sub_C_0_0=1e-9)`
       The keyword paths must match the format generated by `tree_parameter_paths`.
    2. By flat array: `tree_with_parameters(model, flat_params=jnp.array([50.0, 1e-9]))`

    Args:
        tree: The original, immutable PyTree (e.g., an Equinox model).
        flat_params: A 1D JAX array containing all dynamic parameter
                     values in their flattened tree order.
        separator: The default separator used if others are not specified.
        subtree_separator: Separator for nested attribute names.
        array_separator: Separator between attribute path and array index.
        index_separator: Separator for multi-dimensional array indices.
        param_filter: A function that returns `True` for dynamic parameters.
        **params: Keyword arguments where keys are the string paths of the
                  parameters to update and values are their new values.
    """
    # --- Initial argument validation and setup ---
    has_flat = flat_params is not None
    has_kwargs = bool(params)
    param_filter = param_filter or eqx.is_array

    if not has_flat and not has_kwargs:
        return tree

    if has_flat and has_kwargs:
        raise ValueError("Cannot provide both `flat_params` and keyword arguments.")

    # --- Logic Branch 1: Update from a flat array (largely unchanged) ---
    if has_flat:
        params_tree, static = eqx.partition(tree, param_filter)
        flat_leaves, treedef = jax.tree.flatten(params_tree)
        num_expected_params = sum(p.size for p in flat_leaves)
        
        # Ensure input is a JAX array for consistency
        flat_params = np.asarray(flat_params)

        if flat_params.size != num_expected_params:
            raise ValueError(f"Input `flat_params` has size {flat_params.size}, "
                             f"but model requires {num_expected_params}.")

        # Unflatten the leaves into a PyTree with the original structure.
        # Note: JAX can unflatten a 1D array into leaves of various shapes.
        leaves = []
        offset = 0
        for leaf in flat_leaves:
            end = offset + leaf.size
            leaves.append(flat_params[offset:end].reshape(leaf.shape))
            offset = end

        new_params_tree = jax.tree.unflatten(treedef, leaves)
        return eqx.combine(new_params_tree, static)
    
    # --- Logic Branch 2: Update from keyword arguments (rebuilt logic) ---
    if has_kwargs:
        # Set default separators for consistency with tree_parameter_paths
        subtree_separator = subtree_separator if subtree_separator is not None else separator
        array_separator = array_separator if array_separator is not None else separator
        index_separator = index_separator if index_separator is not None else separator
        
        # We will apply updates sequentially. Start with the original tree.
        new_tree = tree

        for path_str, value in params.items():
            # Regex to separate the base path from the array index, e.g., "sub_C" from "[0_0]"
            # It looks for the array_separator followed by anything.
            match = re.match(rf"^(.*?){re.escape(array_separator)}(.*)$", path_str)

            if match:
                base_path_str, index_str = match.groups()
                # Parse index string "0_0" into a tuple of ints (0, 0)
                index = tuple(map(int, index_str.split(index_separator)))
            else:
                base_path_str = path_str
                index = None # This is a scalar or full-array update

            # Parse base path "sub_R" into a list of attribute names ['sub', 'R']
            attr_names = base_path_str.split(subtree_separator)

            # Create the `where` function to navigate to the target attribute
            # `reduce` applies `getattr` sequentially to walk the path
            where = lambda m: reduce(getattr, attr_names, m)

            # If there's an index, the `where` function must also apply it
            if index is not None:
                # We need a new lambda to capture the current `where` and `index`
                # This is safer than modifying the lambda in-place
                base_where = where
                where = lambda m: base_where(m)[index]

            # Apply the single update and reassign the tree for the next loop iteration
            new_tree = eqx.tree_at(where, new_tree, value)

        return new_tree
    

def tree_params(
    tree: Any,
    flat: bool = False,
    separator: str | None = '_',
    subtree_separator: str | None = None,
    array_separator: str | None = None,
    index_separator: str | None = None,
    param_filter: Callable[[Any], bool] | None = None,
) -> Dict[str, Any] | jax.Array:
    """
    Returns the dynamic parameters of a PyTree as either a dictionary of
    paths and values, or a single flattened JAX array.

    The order of the returned paths and values precisely matches the order
    from `jax.tree_util.tree_flatten`.

    Args:
        tree: The PyTree (e.g., an Equinox model) to inspect.
        flat: If `True`, returns a single 1D JAX array of all scalar parameter
              values. If `False` (default), returns a dictionary mapping
              human-readable string paths to their scalar values.
        separator: The default separator used if others are not specified.
        subtree_separator: Separator for nested attribute names.
        array_separator: Separator between attribute path and array index.
        index_separator: Separator for multi-dimensional array indices.
        param_filter: A function that returns `True` for dynamic parameters.

    Returns:
        If `flat=False`, a dictionary of parameter names/paths and values.
        If `flat=True`, a single 1D JAX array of all parameter values.
    """
    param_filter = param_filter or eqx.is_array
    params_tree, _ = eqx.partition(tree, param_filter)

    # --- Logic Branch 1: Return a flattened array ---
    if flat:
        # Get the list of JAX arrays (the "leaves" of the PyTree)
        flat_leaves, _ = jax.tree.flatten(params_tree)
        if not flat_leaves:
            return np.array([]) # Return empty array if no params
        
        # Concatenate all leaves into a single 1D vector
        return np.concatenate([p.ravel() for p in flat_leaves])

    # --- Logic Branch 2: Return a dictionary of paths and values ---
    # Set default separators, only needed for the dictionary case
    subtree_separator: str = subtree_separator if subtree_separator is not None else separator
    array_separator: str = array_separator if array_separator is not None else separator
    index_separator: str = index_separator if index_separator is not None else separator

    paths_and_leaves = jax.tree.leaves_with_path(params_tree)

    parameters = {}
    for path, leaf in paths_and_leaves:
        # Convert path tuple to a human-readable string, e.g., "sub.R"
        path_str = subtree_separator.join(key.name for key in path if isinstance(key, GetAttrKey))

        if leaf.ndim == 0:
            parameters[path_str] = leaf
        else:
            # For array parameters, create an entry for each scalar element
            for index in ndindex(leaf.shape):
                index_str = index_separator.join(map(str, index))
                parameters[f"{path_str}{array_separator}{index_str}"] = leaf[index]
    
    return parameters