"""
Discrepancy modeling between an RF model and actual data.

Useful for modeling discrepancy of RF models during fitting.
"""
from collections.abc import Callable
from abc import abstractmethod

import equinox as eqx
import jax
import jax.numpy as jnp
import distreqx.distributions as dist

from pmrf.utils import field

class AbstractDiscrepancyModel(eqx.Module):
    """
    Abstract base class for discrepancy models.
    
    A discrepancy model maps a model prediction to an updated model prediction.
    This updated prediction can either be deterministic (e.g. a polynomial)
    or probabilistic (e.g. a Gaussian process) by either returning a `JAX` array
    or a `distreqx` probability distribution.
    
    Note that probabilistic discrepancy models operate in "event space".
    Here, probability events (e.g. frequency) are moved to the **last axis**.
    
    These models are commonly used in conjuction with a likelihood function
    via :class:`pmrf.evaluators.MarginalLogLikelihood`.
    
    See :mod:`pmrf.discrepancy_models` for built-in discrepancy models.
    """
    @abstractmethod
    def __call__(self, y_event: jnp.ndarray) -> jnp.ndarray | dist.AbstractDistribution:
        """
        Apply discrepancy correction to a model prediction.

        Parameters
        ----------
        y_event : jnp.ndarray
            The initial model prediction in event space.

        Returns
        -------
        jnp.ndarray | dist.AbstractDistribution
            The updated deterministic or probabilistic prediction.
        """        
        raise NotImplementedError

class GaussianProcess(AbstractDiscrepancyModel):
    """
    Gaussian process discrepancy model with a covariance kernel.
    
    Maps model predictions to a Gaussian Process distribution over frequency.
    
    The kernel is responsible for returning the correlation between two input points.
    Given an input `y` of shape `(*batch_shape, event_dims)`, the kernel must accept
    two inputs (x1, x2) of the same shape (scalar or vector), and return an array
    that is broadcastable to `*batch_shape`.
    
    This easily allows for kernel batching. For example, to create multiple RBF kernels
    that model the last batch dimension D with independent kernels, simply create a kernel
    with parameters of shape (D,).
    
    See :class:`pmrf.DiscrepancyModel` for more information on general discrepancy models.
    See :mod:`pmrf.covariance_kernels` for built-in covariance kernels.

    Parameters
    ----------
    kernel : Callable[[jnp.ndarray, jnp.ndarray], jnp.ndarray]
        The covariance kernel function that computes the correlation between two input arrays.
        Can be a function or a callable PyTree. See :mod:`pmrf.covariance_kernels`
        for built-in covariance kernels.
    jitter : float, default=1e-10
        A small scalar added to the diagonal of the covariance matrix for numerical stability.
    """
    #: The covariance kernel.
    kernel: Callable[[jnp.ndarray, jnp.ndarray], jnp.ndarray]
    
    #: The added jitter.
    jitter: float = field(default=1e-10, static=True)

    def __call__(self, y_event: jnp.ndarray, x: jnp.ndarray, orthogonal_projection: jnp.ndarray | None = None) -> dist.AbstractDistribution:
        """
        Evaluate the Gaussian process distribution over the given inputs.

        Parameters
        ----------
        y_event : jnp.ndarray
            The model prediction in event space, with shape `(..., N)`.
        x : jnp.ndarray
            The frequency points, with shape `(N,)`.
        orthogonal_projection : jnp.ndarray, optional
            An optional matrix P of shape (N, N) which the kernel matrix
            is projected onto using P @ K @ P.T. This can be used to
            specify the subspace which the kernel is allowed.

        Returns
        -------
        dist.AbstractDistribution
            A multivariate normal distribution parameterized by the mean `y_event` 
            and the covariance matrix generated by the kernel.
        """
        x_feat = x[:, None]
        
        inner_vmap = jax.vmap(self.kernel, in_axes=(None, 0), out_axes=-1)
        outer_vmap = jax.vmap(inner_vmap, in_axes=(0, None), out_axes=-2)
        
        K = outer_vmap(x_feat, x_feat) 
        K = K + jnp.eye(x.shape[0]) * self.jitter
        
        if orthogonal_projection is not None:
            K = orthogonal_projection @ K @ orthogonal_projection.T

        target_K_shape = y_event.shape[:-1] + K.shape[-2:]
        K = jnp.broadcast_to(K, target_K_shape)

        init_fn = dist.MultivariateNormalFullCovariance
        for _ in range(y_event.ndim - 1):
            init_fn = eqx.filter_vmap(init_fn)
            
        return init_fn(y_event, K)
    
__all__ = [
    'AbstractDiscrepancyModel',
    'GaussianProcess',
]