import numpy as np
from abc import abstractmethod
import equinox as eqx
import jax.numpy as jnp
from typing import Any


class NodalRepresentation(eqx.Module):
    """
    Static topological representation for nodal admittance assembly and reduction.
    """
    #: A 1D array of global row indices mapping local elements to the global Nodal Admittance Matrix (NAM).
    r_idx: np.ndarray

    #: A 1D array of global column indices mapping local elements to the global NAM.
    c_idx: np.ndarray

    #: A 1D array of node indices designated as external (retained after reduction).
    ext_idx: np.ndarray

    #: A 1D array of node indices designated as internal (eliminated via Schur complement).
    int_idx: np.ndarray

    @property
    def num_nodes(self) -> int:
        """The total number of global nodes in the network, including the dummy ground node."""
        return self.ext_idx.shape[0] + self.int_idx.shape[0]    


class MNARepresentation(eqx.Module):
    """
    Static topological representation for Modified Nodal Analysis (MNA) assembly and reduction.
    """
    #: Global row indices mapping local Y elements (Node to Node) to the global MNA matrix.
    y_r_idx: np.ndarray
    #: Global column indices mapping local Y elements (Node to Node) to the global MNA matrix.
    y_c_idx: np.ndarray

    #: Global row indices mapping local B elements (Node to Aux) to the global MNA matrix.
    b_r_idx: np.ndarray
    #: Global column indices mapping local B elements (Node to Aux) to the global MNA matrix.
    b_c_idx: np.ndarray

    #: Global row indices mapping local C elements (Aux to Node) to the global MNA matrix.
    c_r_idx: np.ndarray
    #: Global column indices mapping local C elements (Aux to Node) to the global MNA matrix.
    c_c_idx: np.ndarray

    #: Global row indices mapping local D elements (Aux to Aux) to the global MNA matrix.
    d_r_idx: np.ndarray
    #: Global column indices mapping local D elements (Aux to Aux) to the global MNA matrix.
    d_c_idx: np.ndarray

    #: A 1D array of standard node indices designated as external (retained after reduction).
    ext_idx: np.ndarray

    #: A 1D array of standard node indices designated as internal (eliminated).
    int_idx: np.ndarray

    #: A 1D array of auxiliary indices (inherently internal and eliminated).
    aux_idx: np.ndarray 

    @property
    def num_nodes(self) -> int:
        """The total number of global standard nodes in the network."""
        return self.ext_idx.shape[0] + self.int_idx.shape[0]

    @property
    def num_aux(self) -> int:
        """The total number of global auxiliary variables."""
        return self.aux_idx.shape[0]
 
    
class PortRepresentation(eqx.Module):
    #: Array mapping each active device port to a net ID
    port_to_net_map: np.ndarray

    #: Ordered array of net IDs that act as external ports
    ext_net_ids: np.ndarray

    @property
    def num_ports(self) -> int:
        """The total number of ports across all components in the topology."""
        return self.port_to_net_map.shape[0]        


class ScatteringResult(eqx.Module):
    """
    Data container for the result of a scattering simulation.
    """
    #: The resulting S-parameter matrix.
    s: jnp.ndarray

    #: The characteristic reference impedance of the resulting S-matrix.
    z0: jnp.ndarray

    #: Indicates whether the solver completed successfully, by default True.
    success: bool = True

    #: Arbitrary metrics or diagnostic data generated by the solver, by default None.
    metrics: Any = None


class AdmittanceResult(eqx.Module):
    """
    Data container for the result of an admittance simulation.
    """
    #: The resulting Admittance (Y-parameter) matrix.
    y: jnp.ndarray

    #: Indicates whether the solver completed successfully, by default True.
    success: bool = True

    #: Arbitrary metrics or diagnostic data generated by the solver, by default None.
    metrics: Any = None


class AbstractAdmittanceCircuitSolver(eqx.Module):
    """Abstract base class for solvers that resolve arbitrary circuit networks in the Admittance domain."""
    
    @abstractmethod
    def run(
        self, 
        y_flattened: jnp.ndarray,
        topology: NodalRepresentation, 
    ) -> AdmittanceResult:
        """
        Executes the admittance circuit solving algorithm.

        Parameters
        ----------
        y_flattened : jnp.ndarray
            A 1D array of flattened Y-parameter matrix elements.
        topology : NodalRepresentation
            The static map dictating the nodal assembly and partition logic.

        Returns
        -------
        AdmittanceResult
            The fully solved external Y-parameter result.
        """
        raise NotImplementedError
    

class AbstractMNACircuitSolver(eqx.Module):
    """Abstract base class for solvers that resolve arbitrary circuits using MNA."""
    
    @abstractmethod
    def run(
        self, 
        y_flattened: jnp.ndarray,
        b_flattened: jnp.ndarray,
        c_flattened: jnp.ndarray,
        d_flattened: jnp.ndarray,
        topology: MNARepresentation, 
    ) -> AdmittanceResult:
        """
        Executes the Modified Nodal Analysis circuit solving algorithm.

        Parameters
        ----------
        y_flattened : jnp.ndarray
            A 1D array of flattened Y-block elements.
        b_flattened : jnp.ndarray
            A 1D array of flattened B-block elements.
        c_flattened : jnp.ndarray
            A 1D array of flattened C-block elements.
        d_flattened : jnp.ndarray
            A 1D array of flattened D-block elements.
        topology : MNARepresentation
            The static map dictating the MNA assembly and partition logic.

        Returns
        -------
        AdmittanceResult
            The fully solved external Y-parameter matrix.
        """
        raise NotImplementedError
    

class AbstractScatteringCircuitSolver(eqx.Module):
    """Abstract base class for solvers that resolve arbitrary circuit networks in the Scattering domain."""
    
    @abstractmethod
    def run(
        self, 
        s_block_diagonal: jnp.ndarray,
        z0_ports: jnp.ndarray,
        topology: PortRepresentation, 
    ) -> ScatteringResult:
        """
        Executes the scattering circuit solving algorithm.

        Note on Dangling Ports
        ----------------------
        Implementations MUST safely handle mathematically isolated external ports (where a port 
        in `topology.ext_idx` is the ONLY port on its defined net). To prevent solvers from 
        evaluating these as perfect open circuits (S=1.0), implementations should dynamically inject 
        matched virtual VNA probes (e.g., padding the S-matrix with 0.0s and rewiring the indices) 
        prior to solving.

        Parameters
        ----------
        s_block_diagonal : jnp.ndarray
            A 2D array of shape (N_total, N_total) containing the uncoupled S-parameters 
            of all components placed sequentially along the main diagonal. All off-diagonal 
            elements are exactly zero.
        z0_ports : jnp.ndarray
            A 1D array of shape (N_total,) containing the characteristic impedances for all ports.
        topology : PortRepresentation
            The static map dictating the port connections, nets, and partition logic.

        Returns
        -------
        ScatteringResult
            The fully solved S-parameter result.
        """
        raise NotImplementedError
    
# Type Aliases for solver categories
AbstractCircuitSolver = AbstractScatteringCircuitSolver | AbstractAdmittanceCircuitSolver | AbstractMNACircuitSolver